const carModels = {
  nissan: [
    "Tsuru",
    "NP300",
    "Versa",
    "Sentra",
    "March",
    "Altima",
    "NP300",
    "X-Trail",
    "Kicks",
    "Maxima",
    "Murano",
    "Armada",
    "Frontier",
    "Leaf",
    "Pathfinder",
    "Rogue",
  ],
  chevrolet: [
    "Aveo",
    "Spark",
    "Sonic",
    "Onix",
    "Trax",
    "Equinox",
    "Malibu",
    "Silverado",
    "Tornado",
    "Cavalier",
    "Blazer",
    "Captiva",
  ],
  volkswagen: ["Jetta", "Vento", "Gol", "Polo", "Tiguan", "Golf", "Saveiro", "Virtus", "T-Cross", "Nivus", "Taos"],
  ford: [
    "Escape",
    "Focus",
    "Fusion",
    "Edge",
    "Explorer",
    "Ecosport",
    "Ranger",
    "Lobo",
    "Bronco-Sport",
    "Expedition",
    "Maverick",
  ],
  honda: ["Civic", "Accord", "Fit", "CR-V", "HR-V", "Pilot", "Odyssey", "Insight"],
  hyundai: ["Grand-i10", "Accent", "Elantra", "Tucson", "Santa-Fe", "Creta", "Sonata", "Kona", "Palisade", "Venue"],
  toyota: ["Yaris", "Corolla", "Camry", "RAV4", "Highlander", "Hilux", "Avanza", "Prius", "Sienna", "Tacoma"],
  kia: ["Rio", "Forte", "Sportage", "Sorento", "Optima", "Soul", "Stinger", "Niro", "Seltos", "Telluride", "Sonet"],
  mg: ["MG5", "ZS", "HS", "RX5"],
  chrysler: ["Pacifica", "300"],
  dodge: ["Attitude", "Charger", "Durango", "Journey", "Neon"],
  fiat: ["Mobi", "Palio", "Uno", "500", "Ducato", "Argo"],
  seat: ["Ibiza", "Leon", "Ateca", "Arona", "Toledo", "Tarraco"],
  peugeot: ["208", "2008", "3008", "301", "5008", "Rifter"],
  suzuki: ["Swift", "Vitara", "Ignis", "Ciaz", "S-Cross", "Ertiga", "Jimny"],
  renault: ["Kwid", "Duster", "Koleos", "Sandero", "Logan", "Oroch", "Stepway"],
};

export default carModels;
