export const icons = {
  phone: "<img class='card_icon' src='../assets/svg/phone.svg' />",
  male: "<img class='card_icon' src='../assets/svg/male.svg' />",
  female: "<img class='card_icon' src='../assets/svg/female.svg' />",
  number: "<img class='card_icon' src='../assets/svg/number.svg' />",
  colors: "<img class='card_icon' src='../assets/svg/palette_color.svg' />",
  card: "<img class='card_icon' src='../assets/svg/card.svg' />",
  badge: "<img class='card_icon' src='../assets/svg/badge.svg' />",
  mail: "<img class='card_icon' src='../assets/svg/email.svg' />",
  car: "<img class='card_icon' src='../assets/svg/cartype.svg' />",
  greencar: "<img class='car_icon' src='../assets/img/green.png' />",
  blackcar: "<img class='car_icon' src='../assets/img/black.png' />",
  bluecar: "<img class='car_icon' src='../assets/img/blue.png' />",
  redcar: "<img class='car_icon' src='../assets/img/red.png' />",
  purplecar: "<img class='car_icon' src='../assets/img/purple.png' />",
  panic_alert: "<img class='car_icon' src='../assets/svg/panic_alert.svg' />",
  warning_alert: "<img class='car_icon' src='../assets/svg/warning_alert.svg' />",
  add: "<img class='crud-icon' src='../assets/img/add_b.svg' />",
  edit: "<img class='crud-icon' src='../assets/img/edit_blue.svg' />",
  del: "<img class='crud-icon' src='../assets/img/delete_red.svg' />",
  check: "<img class='crud-icon' src='../assets/svg/check.svg'"
}

export const dom_icons = {
  phone: '../assets/svg/phone.svg',
  male: '../assets/svg/male.svg',
  female: '../assets/svg/female.svg',
  number: '../assets/svg/number.svg',
  colors: '../assets/svg/palette_color.svg',
  card: '../assets/svg/card.svg',
  badge: '../assets/svg/badge.svg',
  mail: '../assets/svg/email.svg',
  car: '../assets/svg/cartype.svg',
  greencar: '../assets/img/green.png',
  blackcar: '../assets/img/black.png',
  yellowcar: '../assets/img/yellow.png',
  bluecar: '../assets/img/blue.png', 
  warning_icon: '../assets/svg/warning.svg',
  panic_icon: '../assets/svg/panic.svg', 
  purplecar: '../assets/img/purple.png',
  redcar: '../assets/img/red.png',
  panic_alert: '../assets/svg/panic_alert.svg',
  warning_alert: '../assets/svg/warning_alert.svg',
  add: '../assets/img/add_b.svg',
  edit: '../assets/svg/edit.svg',
  del: '../assets/img/delete_red.svg',
  check: '../assets/svg/check.svg'
}
